apiVersion: v1
kind: Service
metadata:
  name: nvidia-dcgm-mock-exporter
  labels:
    app: nvidia-dcgm-exporter
    opendatahub.io/component: "true"
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: nvidia-dcgm-exporter
  ports:
    - name: gpu-metrics
      port: 9400
      protocol: TCP
      targetPort: 9400
