apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: odh-dashboard
  app.kubernetes.io/part-of: odh-dashboard
resources:
- odh-dashboard-crd.yaml
- odh-quick-start-crd.yaml
- odh-document-crd.yaml
- odh-application-crd.yaml
